name    'tkh-x2go'
version '0.1.0'
source 'https://github.com/st01tkh/puppet-x2go'
author 'st01tkh'
license 'Apache License, Version 2.0'
summary 'X2Go Server on Ubuntu Trusty (for now)'
description 'Installs X2Go Server Ubuntu Trusty (for now)'
project_page 'https://github.com/st01tkh/puppet-x2go'
